server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jihye
    password: 1234
    jdbc-url: jdbc:mysql://192.168.15.214:3306/jihye_db?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      idle-timeout: 10000


# com.mysql.cj.jdbc.Driver